from datetime import date
import torch
import torch.nn as nn
import torch.nn.functional as F


from torch.nn import Module, Dropout
import copy

import torch_scatter

# from .utils import *
# from .ba import BA
# from . import projective_ops as pops

import math
import warnings
import numpy as np 

##为相邻帧分配了加权系数，不同帧的边特征对于时间建模具有不同的作用
##在net.py中进行了修改

##修改soft aggre的方式 加入topk实现更高效的聚合
class SoftAgg_moe(nn.Module):
    def __init__(self, dim=512, expand=True, topk_ratio=0.9):
        super(SoftAgg_moe, self).__init__()
        self.dim = dim
        self.expand = expand
        self.topk_ratio = topk_ratio  # 设置 topk 值
        self.f = nn.Linear(self.dim, self.dim)
        self.g = nn.Linear(self.dim, self.dim)
        self.h = nn.Linear(self.dim, self.dim)

    def forward(self, x, ix):
        _, jx = torch.unique(ix, return_inverse=True)
        
        # 计算 g(x) 并获取其在每组中的 Top-K 权重
        gx = self.g(x)  # g(x) 的形状为 [N, dim]
        
        w = torch_scatter.scatter_softmax(gx, jx, dim=1)  # 原始 softmax 权重 #torch.Size([1, 5120, 384])

        # 获取每个分组中的 Top-K 权重及其索引
        _,num_w,_ = w.shape
        _, topk_indices = torch.topk(w, int(self.topk_ratio*num_w), dim=1) #torch.Size([1, 4608, 384])
        
        # 使用 Top-K 权重对 f(x) 进行加权，并在每组中求和
        topk_mask = torch.zeros_like(w).scatter_(1, topk_indices, 1.0)  # 构建 Top-K 掩码
        
        w_topk = w * topk_mask  # 仅保留 Top-K 权重 #torch.Size([1, 5120, 384])
        # import pdb; pdb.set_trace()
        # 归一化 Top-K 权重，使得每组的 Top-K 权重之和为 1
        # w_topk = w_topk / torch_scatter.scatter_sum(w_topk, jx, dim=1, dim_size=w.size(1))

        # 计算加权和
        y = torch_scatter.scatter_sum(self.f(x) * w_topk, jx, dim=1)

        # 输出处理
        if self.expand:
            return self.h(y)[:, jx]
        return self.h(y)

##
##用transformer代替gru
##vvt

def _trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    # Values are generated by using a truncated uniform distribution and
    # then using the inverse CDF for the normal distribution.
    # Get upper and lower cdf values
    l = norm_cdf((a - mean) / std)
    u = norm_cdf((b - mean) / std)

    # Uniformly fill tensor with values from [l, u], then translate to
    # [2l-1, 2u-1].
    tensor.uniform_(2 * l - 1, 2 * u - 1)

    # Use inverse cdf transform for normal distribution to get truncated
    # standard normal
    tensor.erfinv_()

    # Transform to proper mean, std
    tensor.mul_(std * math.sqrt(2.))
    tensor.add_(mean)

    # Clamp to ensure it's in the proper range
    tensor.clamp_(min=a, max=b)
    return tensor

def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.

    NOTE: this impl is similar to the PyTorch trunc_normal_, the bounds [a, b] are
    applied while sampling the normal with mean/std applied, therefore a, b args
    should be adjusted to match the range of mean, std args.

    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    with torch.no_grad():
        return _trunc_normal_(tensor, mean, std, a, b)

def drop_path(x, drop_prob: float = 0., training: bool = False, scale_by_keep: bool = True):
    """Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).

    This is the same as the DropConnect impl I created for EfficientNet, etc networks, however,
    the original name is misleading as 'Drop Connect' is a different form of dropout in a separate paper...
    See discussion: https://github.com/tensorflow/tpu/issues/494#issuecomment-532968956 ... I've opted for
    changing the layer and argument names to 'drop path' rather than mix DropConnect as a layer name and use
    'survival rate' as the argument.

    """
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = x.new_empty(shape).bernoulli_(keep_prob)
    if keep_prob > 0.0 and scale_by_keep:
        random_tensor.div_(keep_prob)
    return x * random_tensor

class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks).
    """
    def __init__(self, drop_prob: float = 0., scale_by_keep: bool = True):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob
        self.scale_by_keep = scale_by_keep

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training, self.scale_by_keep)

    def extra_repr(self):
        return f'drop_prob={round(self.drop_prob,3):0.3f}'

class Mlp(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.GELU, drop=0., linear=False):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features)
        self.drop = nn.Dropout(drop)
        self.linear = linear
        if self.linear:
            self.relu = nn.ReLU(inplace=True)
        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                m.bias.data.zero_()

    def forward(self, x):
        x = self.fc1(x)
        if self.linear:
            x = self.relu(x)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x

class linearattention(nn.Module):
    def __init__(self, embed_dim, num_heads, fr_ratio=1, se_reduction=2):
        super().__init__()
        self.embed_dim = embed_dim
        self.num_heads = num_heads
		# q, k, v projection
        self.fr = fr_ratio 
        # feature reduction
        self.k_proj = nn.Linear(embed_dim, embed_dim // self.fr)
        self.v_proj = nn.Linear(embed_dim, embed_dim // self.fr)
        self.q_proj = nn.Linear(embed_dim, embed_dim // self.fr)
        
        self.apply(self._init_weights)
        # outprojection
        self.out_proj = nn.Linear(embed_dim//self.fr, embed_dim)
        
        # se block:
        reduction = se_reduction
        self.se_pool = nn.AdaptiveAvgPool1d(1)
        self.se_fc = nn.Sequential(
            nn.Linear(embed_dim, embed_dim // reduction, bias=False),
            nn.ReLU(inplace=True),
            nn.Linear(embed_dim // reduction, embed_dim, bias=False),
            nn.Sigmoid()
        )
        
        self.clip = True
        
    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                m.bias.data.zero_()
    
    def abs_clamp(self, t):
        min_mag = 1e-4
        max_mag = 10000
        sign = t.sign()
        return t.abs_().clamp_(min_mag, max_mag)*sign
        
    def forward(self, query):
        num_heads = self.num_heads
        B, N, C = query.shape
        
        query_se = query.permute(0, 2, 1)
        query_se = self.se_pool(query_se).view(B, C)
        query_se = self.se_fc(query_se).view(B, C, 1)
        
        k =  self.k_proj(query)
        v = self.v_proj(query)
        
        k = k.permute(1, 0, 2)
        v = v.permute(1, 0, 2)
        
        query = query.permute(1,0,2)
        tgt_len, bsz, embed_dim = query.size()
        head_dim = embed_dim // num_heads
        # (L, N, E)
        q = self.q_proj(query)
        
 		# multihead
		# (N, L, h, d)
        q = q.contiguous().view(tgt_len, bsz, num_heads, head_dim//self.fr).transpose(0, 1)
		# (N, S, h, d)
        k = k.contiguous().view(-1, bsz, num_heads, head_dim//self.fr).transpose(0, 1)
		# (N, S, h, d)
        v = v.contiguous().view(-1, bsz, num_heads, head_dim//self.fr).transpose(0, 1)
		# relu
        q = F.relu(q)
        k = F.relu(k)
        
        eps = 1e-4
        kv_ =  torch.matmul(k.permute(0, 2, 3, 1), v.permute(0, 2, 1, 3))  
        if self.clip:
            kv_ = self.abs_clamp(kv_)
            
        k_sum = torch.sum(k, axis=1, keepdim=True) # no einsum                         
        z_ = 1 / (torch.sum(torch.mul(q, k_sum), axis=-1) + eps) # no einsum           
        if self.clip:
            z_ = self.abs_clamp(z_)
            
        attn_output = torch.matmul(q.transpose(1, 2), kv_).transpose(1, 2)
        if self.clip:
            attn_output = self.abs_clamp(attn_output)
        
        # nlhm,nlh -> nlhm
        attn_output = torch.mul(attn_output, z_.unsqueeze(-1))
        if self.clip:
            attn_output = self.abs_clamp(attn_output)
            
        # (N, L, h, d) -> (L, N, h, d) -> (L, N, E)
        attn_output = attn_output.transpose(0, 1).contiguous().view(tgt_len, bsz, embed_dim//self.fr)
        
        attn_output = self.out_proj(attn_output)
        if self.clip:
            attn_output = self.abs_clamp(attn_output)

        # ------------------------------------- se block
        attn_output = attn_output.permute(1,2,0)
        attn_output = attn_output + attn_output * query_se.expand_as(attn_output)
        if self.clip:
            attn_output = self.abs_clamp(attn_output)
        # import pdb; pdb.set_trace()
        attn_output = attn_output.permute(2,0,1)
        # -------------------------------------------------

        attn_output = attn_output.permute(1,0,2)

        return attn_output

class transformer_block(nn.Module):
    def __init__(self, dim, num_heads=4, mlp_ratio=2., drop=0., drop_path=0., act_layer=nn.GELU, norm_layer=nn.LayerNorm, fr_ratio = 1, linear=False, se_ratio=1):
        super().__init__()
        self.norm1 = norm_layer(dim)
        self.attn = linearattention(embed_dim=dim, num_heads=num_heads, fr_ratio = fr_ratio, se_reduction=se_ratio)
        
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        self.norm2 = norm_layer(dim)
        
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.mlp = Mlp(in_features=dim, hidden_features=mlp_hidden_dim, act_layer=act_layer, drop=drop, linear=linear)
        self.apply(self._init_weights)
        
    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                m.bias.data.zero_()
    
    def forward(self, x):
        x = x + self.drop_path(self.attn(self.norm1(x)))
        x = x + self.drop_path(self.mlp(self.norm2(x)))

        return x

###效果不行
def get_window_indices(n, h, w, k):
    # 获取特征图的尺寸： (n, c, h, w)
    # n, _, h, w = features.shape  # 去掉 c 维度，只考虑一个通道
    
    # 生成原始位置的坐标网格
    y = torch.arange(h).view(1, h, 1).expand(n, h, w)  # 高度索引
    x = torch.arange(w).view(1, 1, w).expand(n, h, w)  # 宽度索引
    
    # 生成窗口偏移量的网格 (k x k)
    offset = torch.arange(k) - k // 2  # 偏移量从 -k//2 到 k//2
    offset_y, offset_x = torch.meshgrid(offset, offset, indexing='ij')
    
    # 扩展 offset_y 和 offset_x 到与原图大小匹配
    offset_y = offset_y.view(1, 1, 1, k, k).expand(n, h, w, k, k)
    offset_x = offset_x.view(1, 1, 1, k, k).expand(n, h, w, k, k)
    
    # 扩展 y 和 x 到与窗口大小相同的形状
    y_expanded = y.view(n, h, w, 1, 1).expand(n, h, w, k, k)
    x_expanded = x.view(n, h, w, 1, 1).expand(n, h, w, k, k)
    
    # 计算每个位置的窗口索引
    window_y = (y_expanded + offset_y).clamp(min=0, max=h-1)  # 限制在有效范围内
    window_x = (x_expanded + offset_x).clamp(min=0, max=w-1)  # 限制在有效范围内
    
    # 将 (y, x) 转换为一维索引
    window_indices = window_y * w + window_x  # 转换为一维索引
    
    # 重塑成目标形状 (n, h*w, k*k)
    window_indices = window_indices.view(n, h * w, k * k)
    
    return window_indices

def create_mask(window_indices, h, w):
    n, hw, kk = window_indices.shape  # (n, h*w, k*k)
    
    # 构建一个全为0的mask，大小为 (n, h*w, h*w)
    # import pdb; pdb.set_trace()
    mask = torch.zeros((n, hw, hw), dtype=torch.float32)
    
    # 使用高级索引构建 mask
    # 展开 window_indices 成为 (n, hw, k*k) 的索引位置
    mask = mask.scatter_(2, window_indices, 1)  # 将窗口索引对应的值设为1
    #(n, h*w, h*w)
    return mask

class FullAttention(Module):
    def __init__(self, k1, k2, use_dropout=False, attention_dropout=0.1):
        super().__init__()
        self.use_dropout = use_dropout
        self.dropout = Dropout(attention_dropout)
        self.k1 = k1
        self.k2 = k2
    
    def forward(self, queries, keys, value_local, values, n, h, w, q_mask=None, kv_mask=None):
        """ Multi-head scaled dot-product attention, a.k.a full attention.
        Args:
            queries: [N, L, H, D]
            keys: [N, S, H, D]
            values: [N, S, H, D]
            q_mask: [N, L]
            kv_mask: [N, S]
            
            qk_local_mask: [N, L, S]
        Returns:
            queried_values: (N, L, H, D)
        """
        # Compute the unnormalized attention and apply the masks
        QK = torch.einsum("nlhd,nshd->nlsh", queries, keys)
        if kv_mask is not None:
            QK.masked_fill_(~(q_mask[:, :, None, None] * kv_mask[:, None, :, None]), float('-inf'))

        softmax_temp = 1. / queries.size(3)**.5  # sqrt(D)
        
        if h is not None:
            k1, k2 = self.k1, self.k2
            window_indices_choumi = get_window_indices(n, h, w, k1)
            qk_local_mask_choumi = create_mask(window_indices_choumi, h, w) #n l s
            qk_local_mask_choumi = qk_local_mask_choumi.to(QK.device)
            
            # print(qk_local_mask_choumi.device)
            # print(QK.device)
            
            window_indices_xishu = get_window_indices(n, h, w, k2)
            qk_local_mask_xishu = create_mask(window_indices_xishu, h, w) #n l s
            qk_local_mask_xishu = qk_local_mask_xishu.to(QK.device)
            # print(qk_local_mask_xishu.device)

            #QK_local_choumi = torch.where(qk_local_mask_choumi.unsqueeze(-1) != 0, QK, float('-inf'))
            QK_local_choumi = QK * qk_local_mask_choumi.unsqueeze(-1)
            A_local_choumi = torch.softmax(softmax_temp * QK_local_choumi, dim=2)
            queried_values_local_choumi = torch.einsum("nlsh,nshd->nlhd", A_local_choumi, value_local)
            
            #QK_local_xishu = torch.where(qk_local_mask_xishu.unsqueeze(-1) != 0, QK, float('-inf'))
            QK_local_xishu = QK * qk_local_mask_xishu.unsqueeze(-1)
            A_local_xishu = torch.softmax(softmax_temp * QK_local_xishu, dim=2)
            queried_values_local_xishu = torch.einsum("nlsh,nshd->nlhd", A_local_xishu, value_local)
            
        # Compute the attention and the weighted average
        # softmax_temp = 1. / queries.size(3)**.5  # sqrt(D)
        A = torch.softmax(softmax_temp * QK, dim=2)
        if self.use_dropout:
            A = self.dropout(A)

        queried_values_global = torch.einsum("nlsh,nshd->nlhd", A, values)
        
        return queried_values_global.contiguous(), queried_values_local_choumi.contiguous(), queried_values_local_xishu.contiguous()

class l_and_g_attention(nn.Module):
    def __init__(self,
                 d_model,
                 nhead,
                 k1,
                 k2,
                 m_ratio,
                ):
        super(l_and_g_attention, self).__init__()
        
        self.p_off = False
        self.sp_off = True

        self.dim = d_model // nhead
        self.nhead = nhead
        
        self.m_ratio = m_ratio
        # 下采样：使用2D卷积 + stride进行下采样
        self.down_conv = nn.Conv2d(in_channels=d_model, out_channels=d_model, kernel_size=m_ratio, stride=m_ratio, padding=1)
        #self.up_conv = nn.ConvTranspose2d(in_channels=d_model, out_channels=d_model, kernel_size=3, stride=m_ratio, padding=1)

        # multi-head attention
        self.q_proj = nn.Linear(d_model, d_model, bias=False)
        self.k_proj = nn.Linear(d_model, d_model, bias=False)
        self.v_proj = nn.Linear(d_model, d_model, bias=False)
        self.v_proj_local = nn.Linear(d_model, d_model, bias=False)
        self.attention = FullAttention(k1=k1, k2=k2)
        self.merge = nn.Linear(d_model, d_model, bias=False)

        # feed-forward network
        self.mlp = nn.Sequential(
            nn.Linear(d_model*2, d_model*2, bias=False),
            nn.ReLU(True),
            nn.Linear(d_model*2, d_model, bias=False),
        )

        # norm and dropout
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        
        if self.p_off:
            self.fc_weight = nn.Sequential(
                nn.Linear(d_model, 64),
                nn.ReLU(),
                nn.Linear(64, 1),  # 输出每个位置的窗口大小
                nn.Sigmoid()  # 输出范围归一化为 [0, 1]
            )
        
        if self.sp_off:
            # print('sp')
            self.score = nn.Sequential(
                nn.Conv2d(d_model, d_model // 2, kernel_size=5, padding=2, bias=False),  # 5x5卷积，通道数减半
                nn.BatchNorm2d(d_model // 2),  # BN归一化
                nn.ReLU(inplace=True),  # ReLU激活
                nn.Conv2d(d_model // 2, 1, kernel_size=1, bias=False),  # 1x1卷积，通道数变为1
                nn.Sigmoid()  # Sigmoid激活
            )

    def compute_score_weight(self, feature_map):  
        b, n, c, h, w = feature_map.shape
        feature_map =  feature_map.reshape(-1, c, h, w) 
        sp_score = self.score(feature_map) #bn 1 h w
        bn_s, c_s, h_s, w_s = sp_score.shape
        weight_choumi = sp_score.reshape(bn_s, c_s, -1).permute(0,2,1)#bn hw 1
        weight_xishu = 1 - weight_choumi
        return weight_choumi, weight_xishu
        
    def compute_frequency_energy_weight(self, feature_map):
        """计算特征图的频率域能量"""
        b, n, c, h, w = feature_map.shape
        feature_map =  feature_map.reshape(-1, c, h, w)
        # print('maptype:!!!!!!!!!!!!!!!!!',feature_map.dtype)

        feature_map = feature_map.to(torch.float32)

        feature_map_fft = torch.fft.fft2(feature_map)
        # print(feature_map_fft.dtype)
        energy = torch.abs(feature_map_fft) ** 2
        energy = torch.fft.fftshift(energy, dim=(-2, -1))  # 将频率分量移动到图像中心
        
        # 将频率能量输入到全连接网络
        energy_map = energy.permute(0,2,3,1).reshape(-1,c) # 扁平化每个位置的特征图
        # print("energy_map min:", energy_map.min().item(), "max:", energy_map.max().item())
        energy_map = torch.clamp(energy_map, min=-10, max=10)
        weight_choumi = self.fc_weight(energy_map) #bnhw 1 
        weight_choumi = weight_choumi.reshape(b*n, h*w, 1)
        weight_xishu = 1 - weight_choumi
        return weight_choumi, weight_xishu
        
    def forward(self, x, source, x_mask=None, source_mask=None):
        
        ### x 和 source 是b n c h w
        """
        Args:
            x (torch.Tensor): [N, L, C]
            source (torch.Tensor): [N, S, C]
            x_mask (torch.Tensor): [N, L] (optional)
            source_mask (torch.Tensor): [N, S] (optional)
        """
        ###
        # import pdb; pdb.set_trace()'
        x_ori = x
        
        b, n, c, h0, w0 = x.shape
        x_temp = x.reshape(-1, c, h0, w0)
        x_temp = self.down_conv(x_temp)
        _, c, h, w = x_temp.shape
        x = x_temp.reshape(b,n,c,h,w)
        
        ##输入维度转换
        b, n, c, h, w = x.shape
        # print('x_new', x.shape)
        ##获取权重
        if self.p_off:
            weight_choumi, weight_xishu = self.compute_frequency_energy_weight(x)
        if self.sp_off:
            weight_choumi, weight_xishu = self.compute_score_weight(x)
            
        x = x.reshape(b*n, -1, h*w).permute(0,2,1)
        source = source.reshape(b*n, -1, h*w).permute(0,2,1)
        ###
        
        bs = x.size(0)
        # query, key, value = x, source, source
        query, key, value = x, x, x

        # multi-head attention
        query = self.q_proj(query).view(bs, -1, self.nhead, self.dim)  # [N, L, (H, D)]
        key = self.k_proj(key).view(bs, -1, self.nhead, self.dim)  # [N, S, (H, D)]
        value_local = value
        value = self.v_proj(value).view(bs, -1, self.nhead, self.dim)
        value_local = self.v_proj_local(value_local).view(bs, -1, self.nhead, self.dim)
        message_global, message_local_choumi, message_local_xishu = self.attention(query, key, value_local, value, n=bs, h=h, w=w, q_mask=x_mask, kv_mask=source_mask)  # [N, L, (H, D)]
        
        ##
        message_global = message_global.view(bs, -1, self.nhead*self.dim)
        message_local_choumi = message_local_choumi.view(bs, -1, self.nhead*self.dim)
        message_local_xishu = message_local_xishu.view(bs, -1, self.nhead*self.dim) # [N, L, C]
        message = message_global + weight_choumi * message_local_choumi + weight_xishu * message_local_xishu
        
        message = self.merge(message)
        # message = self.merge(message.view(bs, -1, self.nhead*self.dim))  # [N, L, C]
        message = self.norm1(message)

        # feed-forward network
        message = self.mlp(torch.cat([x, message], dim=2))
        message = self.norm2(message)
        
        output = x + message #torch.Size([1, 2400, 256])
        output = output.reshape(b, n, h, w, c).permute(0,1,4,2,3)
        
        ###
        # import pdb; pdb.set_trace()
        output = output.reshape(-1,c,h,w)
        output = F.interpolate(output, size=(h0, w0), mode='bilinear', align_corners=False)
        output = output.reshape(b,n,c,h0,w0)

        return output + x_ori
### 

class gating_multi_conv(nn.Module):
    def __init__(self,
                 d_model,
                 d_hidden_model,
                 norm_off=True,
                 mul=True,
                ):
        super(gating_multi_conv, self).__init__()
        
        self.norm_off = norm_off
        if self.norm_off:
            self.layernorm_que = nn.LayerNorm(d_model)
            self.layernorm_kv = nn.LayerNorm(d_model)
        self.conv1x1_que= nn.Conv2d(in_channels=d_model, out_channels=d_hidden_model, kernel_size=1, stride=1, padding=0)
        self.conv1x1_kv = nn.Conv2d(in_channels=d_model, out_channels=d_hidden_model, kernel_size=1, stride=1, padding=0)
        
        # 3x3 卷积支路
        self.branch_3x3 = nn.Conv2d(d_hidden_model, d_hidden_model, kernel_size=3, padding=1)
        
        # 5x5 卷积支路
        self.branch_5x5 = nn.Conv2d(d_hidden_model, d_hidden_model, kernel_size=5, padding=2)
        
        # 7x7 卷积支路
        self.branch_7x7 = nn.Conv2d(d_hidden_model, d_hidden_model, kernel_size=7, padding=3)
        
        # gating
        self.gating_conv = nn.Conv2d(d_hidden_model, 3, kernel_size=1)
        
        self.merge = nn.Conv2d(d_hidden_model, d_model, kernel_size=1)
        
        self.mul = mul 
        
    def forward(self, x):
        #
        b, n, c, h0, w0 = x.shape
        x_temp = x.reshape(-1, c, h0, w0)
        
        if self.norm_off:
            x_temp = x_temp.reshape(b*n, c, -1).permute(0,2,1) #bn hw c
            
            x_temp_que = self.layernorm_que(x_temp)
            x_temp_que = x_temp_que.permute(0,2,1).reshape(b*n, c, h0, w0).contiguous()
            
            x_temp_kv = self.layernorm_kv(x_temp)
            x_temp_kv = x_temp_kv.permute(0,2,1).reshape(b*n, c, h0, w0).contiguous()

        else:
            x_temp_que = x_temp
            x_temp_kv = x_temp
    
        #
        x_que = self.conv1x1_que(x_temp_que)
        x_kv = self.conv1x1_kv(x_temp_kv)
        
        #处理x kv 加上moe和gating机制
        out_3x3 = self.branch_3x3(x_kv)
        out_5x5 = self.branch_5x5(x_kv)
        out_7x7 = self.branch_7x7(x_kv)
        
        #通过x_que生成gate
        gating_weights = self.gating_conv(x_que) #n 3 h w
        
        # 对权重应用 Softmax 归一化
        gating_weights = F.softmax(gating_weights, dim=1)  # 归一化权重为 [batch_size, 3, H W]
        
        # 找到每个位置的最小得分和它的索引
        min_scores, min_indices = gating_weights.min(dim=1, keepdim=True)

        # gating_weights[gating_weights == min_scores] = 0    
        
        gating_weights_masked = gating_weights.clone()  # 复制原始的 gating_weights 张量
        gating_weights_masked[gating_weights_masked == min_scores] = 0  # 替换最小得分为零
        
        # output = out_3x3 * gating_weights[:, 0:1, :, :] + out_5x5 * gating_weights[:, 1:2, :, :] + out_7x7 * gating_weights[:, 2:3, :, :]
        output = out_3x3 * gating_weights_masked[:, 0:1, :, :] + out_5x5 * gating_weights_masked[:, 1:2, :, :] + out_7x7 * gating_weights_masked[:, 2:3, :, :]
        
        if self.mul:
            output = output * x_que
        
        output = self.merge(output + x_que)
        
        output = output.reshape(b, n, c, h0, w0).contiguous()
        
        return output
        
###
def elu_feature_map(x):
    return torch.nn.functional.elu(x) + 1

class LinearAttention(Module):
    def __init__(self, eps=1e-6):
        super().__init__()
        self.feature_map = elu_feature_map
        self.eps = eps

    def forward(self, queries, keys, values, q_mask=None, kv_mask=None):
        """ Multi-Head linear attention proposed in "Transformers are RNNs"
        Args:
            queries: [N, L, H, D]
            keys: [N, S, H, D]
            values: [N, S, H, D]
            q_mask: [N, L]
            kv_mask: [N, S]
        Returns:
            queried_values: (N, L, H, D)
        """
        Q = self.feature_map(queries)
        K = self.feature_map(keys)

        # set padded position to zero
        if q_mask is not None:
            Q = Q * q_mask[:, :, None, None]
        if kv_mask is not None:
            K = K * kv_mask[:, :, None, None]
            values = values * kv_mask[:, :, None, None]

        v_length = values.size(1)
        values = values / v_length  # prevent fp16 overflow
        KV = torch.einsum("nshd,nshv->nhdv", K, values)  # (S,D)' @ S,V
        Z = 1 / (torch.einsum("nlhd,nhd->nlh", Q, K.sum(dim=1)) + self.eps)
        queried_values = torch.einsum("nlhd,nhdv,nlh->nlhv", Q, KV, Z) * v_length

        return queried_values.contiguous()

def XNorm(x, gamma):
    norm_tensor = torch.norm(x, 2, -1, True)
    return x * gamma / norm_tensor

class Position_Encoding(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.feature_dim = dim

    @staticmethod
    def embed_rotary(x, cos, sin):
        '''
        @param x: [B,N,d]
        @param cos: [B,N,d]  [θ0,θ0,θ1,θ1,θ2,θ2......θd/2-1,θd/2-1]
        @param sin: [B,N,d]  [θ0,θ0,θ1,θ1,θ2,θ2......θd/2-1,θd/2-1]
        @return:
        '''
        x2 = torch.stack([-x[..., 1::2], x[..., ::2]], dim=-1).reshape_as(x).contiguous()
        x = x * cos + x2 * sin
        return x

    @staticmethod
    def embed_pos(x, pe):
        """ combine feature and position code
        """
        return Position_Encoding.embed_rotary(x, pe[..., 0], pe[..., 1])

    def forward(self, feature):
        bsize, npoint, _ = feature.shape
        position = torch.arange(npoint, device=feature.device).unsqueeze(dim=0).repeat(bsize, 1).unsqueeze(dim=-1)
        # [1, 1, d/2]
        div_term = torch.exp(torch.arange(0, self.feature_dim, 2, dtype=torch.float, device=feature.device) * (
                    -math.log(10000.0) / (self.feature_dim))).view(1, 1, -1)
        sinx = torch.sin(position * div_term)  # [B, N, d//2]
        cosx = torch.cos(position * div_term)
        sinx, cosx = map(lambda feat: torch.stack([feat, feat], dim=-1).view(bsize, npoint, -1), [sinx, cosx])
        position_code = torch.stack([cosx, sinx], dim=-1)
        if position_code.requires_grad:
            position_code = position_code.detach()
        return position_code

class SpatialGate(nn.Module):
    def __init__(self, dim=768):
        super().__init__()
        self.norm = nn.LayerNorm(dim)
        self.conv = nn.Conv2d(dim, dim, kernel_size=3, stride=1, padding=1, bias=True, groups=dim) # DW Conv

    def forward(self, x):
        # Split
        x1, x2 = x.chunk(2, dim = -1)
        B, N, C = x.shape
        if N == 4800:
            H, W = 60, 80
        else:
            H, W = int(N ** 0.5), int(N ** 0.5)
        x2 = self.conv(self.norm(x2).transpose(1, 2).contiguous().view(B, C//2, H, W)).flatten(2).transpose(-1, -2).contiguous()

        return x1 * x2

##input n l c 
class linear_module(nn.Module):
    def __init__(self,
                 d_model,
                 nhead,
                 attention='linear',
                 iscoarse=False):
        super(linear_module, self).__init__()

        self.dim = d_model // nhead
        self.nhead = nhead

        # multi-head attention
        self.q_proj = nn.Linear(d_model, d_model, bias=False)
        self.k_proj = nn.Linear(d_model, d_model, bias=False)
        self.v_proj = nn.Linear(d_model, d_model, bias=False)
        self.attention = LinearAttention() if attention == 'linear' else FullAttention()
        self.merge = nn.Linear(d_model, d_model, bias=False)

        # feed-forward network
        if iscoarse == True:
            self.mlp = nn.Sequential(
                nn.Linear(d_model*2, d_model*4, bias=False),
                SpatialGate(d_model*2),
                nn.GELU(),
                nn.Linear(d_model*2, d_model, bias=False),
            )
        else:
            self.mlp = nn.Sequential(
                nn.Linear(d_model*2, d_model*4, bias=False),
                nn.GELU(),
                nn.Linear(d_model*4, d_model, bias=False),
            )

        # norm and dropout
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.rotary_emb = Position_Encoding(dim=d_model)
        self.gamma=nn.Parameter(torch.randn((1, self.nhead, 1, 1)))

    def forward(self, x, source, x_mask=None, source_mask=None):
        """
        Args:
            x (torch.Tensor): [N, L, C]
            source (torch.Tensor): [N, S, C]
            x_mask (torch.Tensor): [N, L] (optional)
            source_mask (torch.Tensor): [N, S] (optional)
            
        """

        # import pdb; pdb.set_trace()

        bs = x.size(0)
        query, key, value = x, source, source

        # multi-head attention
        mixed_query_layer = self.q_proj(query)
        mixed_key_layer = self.k_proj(key)
        que_pe = self.rotary_emb(mixed_query_layer)
        key_pe = self.rotary_emb(mixed_key_layer)
        query = Position_Encoding.embed_pos(mixed_query_layer, que_pe).view(bs, -1, self.nhead, self.dim).permute(0, 2, 1, 3)   # [B H N C]
        key = Position_Encoding.embed_pos(mixed_key_layer, key_pe).view(bs, -1, self.nhead, self.dim).permute(0, 2, 3, 1)   # [B H C N]
        
        value = self.v_proj(value).view(bs, -1, self.nhead, self.dim).permute(0, 2, 1, 3)   # [B H N C]

        kv = torch.matmul(key, value) #bs,h,c,c
        kv_norm = XNorm(kv, self.gamma) #bs,h,c,c
        q_norm = XNorm(query, self.gamma) #bs, h, n, c
        message = torch.matmul(q_norm,kv_norm).permute(0, 2, 1, 3).contiguous()

        # message = self.attention(query, key, value, q_mask=x_mask, kv_mask=source_mask)  # [N, L, (H, D)]
        message = self.merge(message.view(bs, -1, self.nhead*self.dim))  # [N, L, C]
        message = self.norm1(message)

        # feed-forward network
        message = self.mlp(torch.cat([x, message], dim=2))
        message = self.norm2(message)

        return x + message

class g_en_module(nn.Module):
    def __init__(self, 
                 d_model,
                 nhead,
                 attention='linear',
                 iscoarse=False):
        super(g_en_module,self).__init__()
        self.d_model = d_model
        self.nhead = nhead
        self.attention = attention
        self.iscoarse = iscoarse
        self.linear_module = linear_module(
                 d_model=self.d_model,
                 nhead=self.nhead,
                 attention=self.attention,
                 iscoarse=self.iscoarse)
    
    def forward(self, x):
        x_ori = x
        # import pdb; pdb.set_trace()
        
        ##输入维度转换
        b_s, n_s, c_s, h_s, w_s = x.shape
        x = x.reshape(b_s*n_s, -1, h_s*w_s).permute(0,2,1) #b l c
        
        output = self.linear_module(x=x, source=x, x_mask=None, source_mask=None)
        
        output = output.permute(0,2,1).reshape(b_s, n_s, c_s, h_s, w_s)
        
        return output

#### 用全局上下文信息增强patch图
## fmap #torch.Size([1, 1, 128, 160, 88])
## patch #torch.Size([1, 96, 128, 3, 3])
## 输出也是([1, 96, 128, 3, 3])

class g_to_p_Attention(Module):
    def __init__(self, use_dropout=False, attention_dropout=0.1):
        super().__init__()
        self.use_dropout = use_dropout
        self.dropout = Dropout(attention_dropout)
    
    def forward(self, queries, keys, values, q_mask=None, kv_mask=None):
        """ Multi-head scaled dot-product attention, a.k.a full attention.
        Args:
            queries: [N, L, H, D]
            keys: [N, S, H, D]
            values: [N, S, H, D]
            q_mask: [N, L]
            kv_mask: [N, S]
            
            qk_local_mask: [N, L, S]
        Returns:
            queried_values: (N, L, H, D)
        """
        # Compute the unnormalized attention and apply the masks
        QK = torch.einsum("nlhd,nshd->nlsh", queries, keys)
        if kv_mask is not None:
            QK.masked_fill_(~(q_mask[:, :, None, None] * kv_mask[:, None, :, None]), float('-inf'))

        softmax_temp = 1. / queries.size(3)**.5  # sqrt(D)
            
        # Compute the attention and the weighted average
        # softmax_temp = 1. / queries.size(3)**.5  # sqrt(D)
        A = torch.softmax(softmax_temp * QK, dim=2)
        
        ###用于可视化
        # 第一步：对第四个维度（dim=3）进行求和
        # summed_tensor = A.sum(dim=-1)  # 结果形状: [1, 96, 4408]
        # # 第二步：消除第一个维度（dim=0）
        # result_tensor = summed_tensor.squeeze(0)  # 结果形状: [96, 4408]
        # print('result_tensor', result_tensor.shape)
        # reshaped_tensor = result_tensor.reshape(96, 58, 76)
        # print(f"重塑后的形状: {reshaped_tensor.shape}")

        # # 2. 对第一个维度(96)求和，得到(58, 76)的张量
        # summed_tensor = reshaped_tensor.sum(dim=0)
        # print(f"求和后的形状: {summed_tensor.shape}")   
        # numpy_array = summed_tensor.detach().cpu().numpy()
        # np.save('attention_matrix_58x76.npy', numpy_array)
        # print("已保存为NumPy格式文件: attention_matrix_58x76.npy")
        # exit()
    
        
        
        if self.use_dropout:
            A = self.dropout(A)

        queried_values_global = torch.einsum("nlsh,nshd->nlhd", A, values)
        
        return queried_values_global.contiguous()

class g_to_p_module(nn.Module):
    def __init__(self,
                 d_model,
                 nhead,
                ):
        super(g_to_p_module, self).__init__()

        self.dim = d_model // nhead
        self.nhead = nhead
        
        # multi-head attention
        self.q_proj = nn.Linear(d_model, d_model, bias=False)
        self.k_proj = nn.Linear(d_model, d_model, bias=False)
        self.v_proj = nn.Linear(d_model, d_model, bias=False)
        self.v_proj_local = nn.Linear(d_model, d_model, bias=False)
        self.attention = g_to_p_Attention()
        self.merge = nn.Linear(d_model, d_model, bias=False)

        # feed-forward network
        self.mlp = nn.Sequential(
            nn.Linear(d_model*2, d_model*2, bias=False),
            nn.ReLU(True),
            nn.Linear(d_model*2, d_model, bias=False),
        )

        # norm and dropout
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        
        self.adaptive_pool = nn.AdaptiveAvgPool2d(1)
        self.conv_fuse = nn.Conv2d(in_channels=2*d_model, out_channels=d_model, kernel_size=1)

    def forward(self, x, source, x_mask=None, source_mask=None):
        
        ###source 是b n c h w
        """
        Args:
            x (torch.Tensor): [N, L, C]
            source (torch.Tensor): [N, S, C]
            x_mask (torch.Tensor): [N, L] (optional)
            source_mask (torch.Tensor): [N, S] (optional)
        """
        ###
        # import pdb; pdb.set_trace()'
        x_ori = x
        
        ##输入维度转换
        b_s, n_s, c_s, h_s, w_s = source.shape
        
        
        source_tmp = source.reshape(-1, c_s, h_s, w_s)
        output_size = (h_s // 2, w_s // 2)
        # print(h_s, w_s, output_size)
        # exit()
        source_tmp = torch.nn.functional.adaptive_avg_pool2d(source_tmp, output_size)
        b_s_new, c_s, h_s, w_s = source_tmp.shape
        source = source_tmp.reshape(b_s, n_s,c_s, h_s, w_s)
        
    
        # x_temp = self.down_conv(x_temp)
        # _, c, h, w = x_temp.shape
        # x = x_temp.reshape(b,n,c,h,w)
        
        source = source.reshape(b_s*n_s, -1, h_s*w_s).permute(0,2,1) #b l c

        ###
        # 假设你的输入张量是：
        b, pn, c, psize_0, psize_1 = x.shape #(1, 96, 128, 3, 3)
        
        x = x.reshape(-1, c, psize_0, psize_1)  # 变成 [96, 128, 3, 3]
        x_tmp_1 = x 

        # 定义自适应池化层，将空间维度压缩为 1
        x = self.adaptive_pool(x) #变成 [96, 128, 1, 1]

        x = x.reshape(b * pn, c).reshape(b, pn, c)

        ##
        bs = x.size(0)
        query, key, value = x, source, source

        # multi-head attention
        query = self.q_proj(query).view(bs, -1, self.nhead, self.dim)  # [N, L, (H, D)]
        key = self.k_proj(key).view(bs, -1, self.nhead, self.dim)  # [N, S, (H, D)]
        value = self.v_proj(value).view(bs, -1, self.nhead, self.dim)
        
        message_global = self.attention(query, key, value, q_mask=x_mask, kv_mask=source_mask)  # [N, L, (H, D)]
        
        ##
        message_global = message_global.view(bs, -1, self.nhead*self.dim)
        message = message_global
        
        message = self.merge(message)
        # message = self.merge(message.view(bs, -1, self.nhead*self.dim))  # [N, L, C]
        message = self.norm1(message)

        # feed-forward network
        message = self.mlp(torch.cat([x, message], dim=2))
        message = self.norm2(message) #b pn c
        
        ##
        message = message.reshape(b*pn, c).unsqueeze(-1).unsqueeze(-1) #b*pn,c,1,1
        
        message = message.expand(-1,-1, psize_0, psize_1)
        output = torch.cat([message, x_tmp_1], dim=1) 
        output = self.conv_fuse(output)
        output = output.reshape(b, pn, c, psize_0, psize_1)
    
        return output
    
# import torch
# import torch.nn as nn
# import torch.nn.functional as F

class DynamicConv2d(nn.Module):  # IDConv
    def __init__(self,
                dim,
                kernel_size=3,
                reduction_ratio=4,
                num_groups=1,
                bias=True):
        super().__init__()
        assert num_groups > 1, f"num_groups {num_groups} should > 1."
        self.num_groups = num_groups
        self.K = kernel_size
        self.bias_type = bias
        self.weight = nn.Parameter(torch.empty(num_groups, dim, kernel_size, kernel_size), requires_grad=True)
        self.pool = nn.AdaptiveAvgPool2d(output_size=(kernel_size, kernel_size))
        # 替换 ConvModule
        self.proj = nn.Sequential(
            nn.Conv2d(dim, dim // reduction_ratio, kernel_size=1),
            nn.BatchNorm2d(dim // reduction_ratio),
            nn.GELU(),
            nn.Conv2d(dim // reduction_ratio, dim * num_groups, kernel_size=1)
        )

        if bias:
            self.bias = nn.Parameter(torch.empty(num_groups, dim), requires_grad=True)
        else:
            self.bias = None

        self.reset_parameters()

    def reset_parameters(self):
        nn.init.trunc_normal_(self.weight, std=0.02)
        if self.bias is not None:
            nn.init.trunc_normal_(self.bias, std=0.02)

    def forward(self, x):
        B, C, H, W = x.shape
        scale = self.proj(self.pool(x)).reshape(B, self.num_groups, C, self.K, self.K)
        scale = torch.softmax(scale, dim=1)
        weight = scale * self.weight.unsqueeze(0)
        weight = torch.sum(weight, dim=1, keepdim=False)
        weight = weight.reshape(-1, 1, self.K, self.K)

        if self.bias is not None:
            scale = self.proj(torch.mean(x, dim=[-2, -1], keepdim=True))
            scale = torch.softmax(scale.reshape(B, self.num_groups, C), dim=1)
            bias = scale * self.bias.unsqueeze(0)
            bias = torch.sum(bias, dim=1).flatten(0)
        else:
            bias = None

        x = F.conv2d(x.reshape(1, -1, H, W),
                    weight=weight,
                    padding=self.K // 2,
                    groups=B * C,
                    bias=bias)

        return x.reshape(B, C, H, W)
    
# if __name__ == "__main__":
#     print('tes')
#     B, C, H, W = 2, 256, 120, 60
#     x = torch.randn(B, C, H, W)
#     # 实例化 DynamicConv2d 类
#     conv = DynamicConv2d(dim=C, num_groups=2)
#     # 进行前向传播
#     output = conv(x)
#     print(output.shape)
# export NCCL_P2P_LEVEL=NVL
# CUDA_VISIBLE_DEVICES=6,7,8,9 torchrun --standalone --nproc_per_node=4 train_multi_gpu.py --steps=240000 --lr=0.00008 --name=gao0210



if __name__ == "__main__":
    # n, l, c = 1, 10000, 256
    # A = torch.rand(n, l, c)
    # # function = linearattention(embed_dim=256, num_heads=4, fr_ratio=1, se_reduction=2)
    # function = transformer_block(c, num_heads=4, mlp_ratio=2., drop=0.1, drop_path=0., act_layer=nn.GELU, norm_layer=nn.LayerNorm, fr_ratio = 1, linear=False, se_ratio=1)
    # output = function(A)
    # print('ok')
    b, n, c, h, w = 1, 1, 128, 160, 88
    features = torch.randn(b, n, c, h, w)
    
    # module = l_and_g_attention(d_model=256, 
    #                            nhead=4, 
    #                            k1=3, 
    #                            k2=7,
    #                            m_ratio=4)
    # features_new = module(x=features, source=features) 
    
    # module = gating_multi_conv(d_model=128, d_hidden_model=256)
    
    # que = torch.randn(1, 96, 128, 3, 3)
    # module = g_to_p_module(d_model=128, 
    #                            nhead=4)
    # features_new = module(x=que, source=features) 
    
    
    module = g_en_module(d_model=128,
                 nhead=4,
                 attention='linear',
                 iscoarse=False)
    
    features_new = module(x=features)
    
    print(features_new.shape)
    print('ok')